
export interface StoreSettings {
  addPrintDateOnBarcodePrinting: boolean;
  adviserCodePrefix: string;
  adviserGroupCodePrefix: string;
  allowConnectivityNotesOnChainStores: boolean;
  allowDeleteProductsOnNotes: boolean;
  allowDeliverOverQuantity: boolean;
  allowFilterDateRangePeriodicDrugQualityControl: boolean;
  allowFilterDateRangeRevenueReportByDays: boolean;
  allowSyncProdConnInfos: boolean;
  allowToChangeNoteDateToPassDay: boolean;
  allowToChangeTotalAmount: boolean;
  allowUserInputDuplicatedItems: boolean;
  applyAllCategoriesForAllInChains: boolean;
  archiveDataAfterDays: number;
  archiveDataAfterDays_Activated: boolean;
  autoConnectivityPrescriptionNoteToDTQG: boolean;
  autoCreateBarcode: boolean;
  autoCreateProductCode: boolean;
  autoGenReceiptReport: boolean;
  autoLockNotesAfterDays: number;
  autoLockNotesAfterDays_Activated: boolean;
  autoPrintTypeAfterDeliveryNote: number;
  autoPrintTypeAfterDeliveryNote_Activated: boolean;
  autoPullOrderToExpressServices: boolean;
  autoSynchronizeDeliveryNote: boolean;
  autoSynchronizeReceiptNote: boolean;
  autoUpdateOutPriceForGeneralStore: boolean;
  batchExpInReceiptDeliveryNotes: boolean;
  costsAccountNumber: string;
  customerCareIntegration: boolean;
  customerCodePrefix: string;
  customerGroupCodePrefix: string;
  defaultApproveName: string;
  defaultDirectorName: string;
  defaultExaminationService: string;
  defaultExaminationService_Activated: boolean;
  deliveryNoteDiscountByValue: boolean;
  deliveryNoteDiscountTotalByValue: boolean;
  displayDosage: boolean;
  displayHistoryTable: boolean;
  electronicScalesCode: string;
  enableAutoDelivery: boolean;
  enableClinic: boolean;
  enableCombo: boolean;
  enableComboNotes: boolean;
  enableCreateDateNotes: boolean;
  enableCustomPrices: boolean;
  enableElectronicInvoice: boolean;
  enableExcelImportTemplateConfiguration: boolean;
  enableExtraCustomICD10: string | null;
  enableExtraCustomICD10_Activated: boolean;
  enableFeedDataForSearchEngine: boolean;
  enableFreeStore: boolean;
  enableInputEInvoiceIntegrate: boolean;
  enableInvoiceProduct: boolean;
  enableLogisticsWarehouse: boolean;
  enablePaymentStatuses: boolean;
  enableProductSyncNote: boolean;
  enableQRPayment: boolean;
  enableSellerOrderingSupervisor: boolean;
  enableTransObjectDetails: boolean;
  enableVATOnNoteItem: boolean;
  enableZNS: boolean;
  firstShiftMoney: boolean;
  internalManagement: boolean;
  inventoryAccountNumber: string;
  inventoryCapitalAccountNumber: string;
  inventoryCode: string;
  limitQuantityProductForOrder: boolean;
  maturityServiceViaCreditCard: boolean;
  notAutoCombineDuplicatedItemsOnNotes: boolean;
  notAutoUpdateInOutNameOnNoteKey: boolean;
  notAutoUpdateInOutPriceOnNote: boolean;
  numberDaysNearExpiredDate: number;
  numberDaysNoTransaction: number;
  onlyDisplayOrderingFeatures: boolean;
  orderDiscountPercent: number;
  orderDiscountPercent_Activated: boolean;
  prescriptionNoteToDeliveryNote: boolean;
  printDeliveryPrescribedFrom: boolean;
  printScoreOnBill: boolean;
  processBatchNumberAndExpDateFromName: boolean;
  productCodePrefix: string;
  productGroupCodePrefix: string;
  receiptNoteDiscountByValue: boolean;
  reportDetailsByGoods: boolean;
  requireAcceptTranferNotes: boolean;
  revenueAccountNumber: string;
  settingOwnerPrices: boolean;
  settingOwnerPrices_Activated: boolean;
  showScoreStaff: boolean;
  staffCodePrefix: string;
  storeComboId: string;
  storeInfosSearchable: boolean;
  supplierCodePrefix: string;
  supplierGroupCodePrefix: string;
  supportExportEInvoices: boolean;
  targetStoreIds4SynNotes: string;
  targetStoreIds4SynNotes_Activated: boolean;
  tranferStoreIds: string;
  turnOffAcceptancePendingImportNotes: boolean;
  turnOffNoteLockAfterInventory: boolean;
  uniqueProductByCodeAndName: boolean;
  uniqueProductByName: boolean;
  updateImagesForProducts: boolean;
  usePointsOnProductMethod: boolean;
  [key: string]: any;
}

export interface DefaultEntityInfo {
  id: number;
  code: string;
  name: string;
  score: number;
}

export interface DefaultStoreIds {
  customerGroupId: number;
  defaultUserGroupId: number;
  supplierGroupId: number;
  productGroupId: number;
  productGroupNormalId: number;
  productGroupServiceId: number;
  productGroupComboId: number;
  staffGroupId: number;
  retailCustomerId: number;
  retailSupplierId: number;
  inventoryAdjCustomerId: number;
  internalCustomerId: number;
  internalSupplierId: number;
  inventoryAdjSupplierId: number;
  defaultUserId: number;
  defaultPaymentTypeId: number;
  retailCustomer: DefaultEntityInfo;
  retailSupplier: DefaultEntityInfo;
  [key: string]: any;
}

export interface StoreSession {
  id: number;
  code: string;
  masterId: number;
  refStoreId: number;
  classificationId: number;
  businessTypeId: number;
  storeName: string;
  storeAddresses: string | null;
  storePhones: string | null;
  storeMobiles: string | null;
  storeTaxCode: string | null;
  isMasterStore: boolean;
  isSlaveStore: boolean;
  defaultIds: DefaultStoreIds;
  settings?: StoreSettings;
  [key: string]: any;
}
export interface HomeViewModelData {
  session: StoreSession;
  settings: StoreSettings;
}
